### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by nabilfreeman**
NB - Not ready to merge yet.

screenshot 2015-07-27 23 40 35

### CODE REVIEW

**Comment by greyhwndz** [comment]
@nabilfreeman: I like how it's turning out :+1:

**Comment by locks** [comment]
@nabilfreeman what's the status on this?

**Comment by locks** [comment]
@nabilfreeman what's it missing?

**Comment by locks** [comment]
We took these ideas and incorporated them in the [Ember port](http://architect-bat-75067.netlify.com/). You can see more details in the related PR.
Thanks for the initial push @nabilfreeman! If you want to get back into the fray, ping us on Slack :)

**Comment by nabilfreeman** [comment]
You're most welcome! Sorry this stagnated for so long 😁

**Pull request closed without merging**
