### PR TITLE
finished a tile view for the books page and added thumbnails to youtube vids

### PR DESCRIPTION
**Pull request by nabilfreeman**
Breakdown of the stuff in this PR
- Small design change to the top nav bar to a "light mode" - allows greater focus on the content of the page
- A tile layout on the books page - This has been built in a way that we can extend it to the other pages such as videos, screencasts etc. We can also customise the appearance of the tiles to fit the content that they are representing. See how the book tiles are actually formatted like books!
- Youtube videos now show thumbnails as part of the play button. I have also designed the thumbnails to extend to the other pages eventually, when we might want to pull in rich media such as og:image tags etc, and even vimeo, soundcloud etc.

NB: I was working on a switchable tile view for the videos page because I thought it would be pretty cool, but the tile view turned out not to be very useful in any way apart from big thumbnails.

Some of the code has been worked for that so would like to hear what you think @pootsbook about it.

### CODE REVIEW

**Comment by nabilfreeman** [comment]
Just gonna add images and hook up a couple of loose wires...

**Comment by nabilfreeman** [comment]
Before:

screenshot 2015-07-03 13 10 59

After:

screenshot 2015-07-03 13 10 39

**Comment by nabilfreeman** [comment]
Before:

screenshot 2015-07-03 13 12 01

After:

screenshot 2015-07-03 13 22 26

**Comment by nabilfreeman** [comment]
screenshot 2015-07-03 13 24 24

^^^ abandoned tile view for videos. inline playback required some crazy code (like what happens when you click a photo on Google Images) and the lack of metadata made me put it to the site and just focus on the books

**Comment by pootsbook** [comment]
Hey @nabilfreeman, it all looks good. I love the book tile view, really nice.

In terms of Video tile view, we can maybe pull that in whenever we have a dedicated page for each video, so the video link, instead of playing inline, takes you to the video page with autoplay. But this is good for now.

**Comment by nabilfreeman** [comment]
yeah! i like that idea. another option is potentially just opening a new tab/window with the video URL

**Pull request merged**
