### PR TITLE
[New Article] Closure Actions have Return Values

### PR DESCRIPTION
**Pull request by greyhwndz**

### CODE REVIEW

**Comment by pootsbook** [comment]
Merged in 276c2d0db437ce033018efb6012d95bef5cf5566

**Comment by greyhwndz** [comment]
Thanks @pootsbook !

**Comment by pootsbook** [comment]
You’re welcome @greyhwndz . My process for dealing with commits that don’t merge cleanly is as follows:
1. Pull down the PR into a separate branch. See [GitHub Docs](https://help.github.com/articles/checking-out-pull-requests-locally/).  
   `git fetch origin pull/<id>/head:<branchname>`
2. `git checkout <branchname>`
3. `git rebase gh-pages`
4. Solve the merge conflict by editing the file(s).
5. `git add <uncommitted-files>`
6. `git rebase --continue`  
   _repeat steps 4–6 until clean_ 
7. `git checkout gh-pages`
8. `git merge <branchname>`  
   _this will be a fast-forward merge_

**Comment by greyhwndz** [comment]
hey @pootsbook! Thanks for sharing that process! The info above is highly appreciated! :+1: Would definitely check that out for commits that don't merge cleanly. :)
Just a question though, I have a EW forked and I had it cloned locally. I had the original EW repo as `upstream` not as `origin`. Should the `origin` above refer to the original EW repo?

**Comment by pootsbook** [comment]
Yeah, sorry, I'm assuming above that `origin` is GitHub’s emberwatch/emberwatch.

**Comment by greyhwndz** [comment]
@pootsbook Nevertheless, it was really helpful. Thanks again :)

**Pull request closed without merging**
