### PR TITLE
[WIP] Cookbook recipes

### PR DESCRIPTION
**Pull request by locks**
Adds recipes from the Ember.js guides.
- [ ] Proper TOC

### CODE REVIEW

**Comment by locks** [comment]
@pootsbook what's the most lazy way for the Cookbook page to generate a nice TOC for the collection and have the links work? I have 0 familiarity with Jekyll at the moment.

**Comment by locks** [comment]
much to do
EmberWatch cookbook recipe
EmberWatch cookbook listing

**Comment by pootsbook** [comment]
This is a great start @locks, thanks. I know you are pretty busy at the moment, so I'm going to merge this, add a disclaimer that it is a work in progress, and ship it :shipit: 

I can clean it up and get it looking similar to how it was. If there is anything specific you want me to focus on, then open an issue with a to-do list and I can get cracking.

**Comment by locks** [comment]
:heart:

**Comment by mixonic** [comment]
FWIW the cookbooks are now removed from the guides repo: https://github.com/emberjs/guides/pull/411 this change is not yet deployed, but will be soon.

**Pull request merged**
