### PR TITLE
Added Components tab and some content

### PR DESCRIPTION
**Pull request by taras**
I created a components.yml file and updated index.html.erb to display those components.
I never really used ruby tools so I don't know how to make this database available in the index.html.erb template.

I'm getting an error when I try to view the site.

Could you look into the cause of the problem?

### CODE REVIEW

**Comment by pootsbook** [comment]
Hey @taras 

I've pulled your code into a ["components" branch](https://github.com/emberwatch/emberwatch-source/tree/components) branched off master.

There were two errors. 
1. The cause of the first was referencing two people that did not yet exist, ids 62, 63. I've put placeholders in for now.
2. The cause of the second was using `empty?` instead of `nil?`. You can read more about the difference between `empty?`, `nil?` and `blank?` on [ruby-forum](https://www.ruby-forum.com/topic/160638)

If you fill out the names of the other contributors I'll be happy to merge it into master and deploy it. You can do that through the GitHub editor if that's quicker and easier.

One note though, I believe Yehuda Katz' Bootstrap project is very out of date. It might be worth replacing it with [ember-app-kit](https://github.com/stefanpenner/ember-app-kit).

Thanks so much for your contribution,

Philip

**Comment by taras** [comment]
I was making those changes very late at night so something went funky. I added the missing people and replaced Bootstrap with Ember Bootstrap ( which I meant to include )

**Comment by pootsbook** [comment]
Thanks for your help @taras. Sorry it took me a week to get round to merging this in. 

I've just made one change, renaming "Components" to "Libraries". I want to avoid confusion with an [Ember Component](http://emberjs.com/api/classes/Ember.Component.html) which is something quite distinct.

**Comment by taras** [comment]
Np, thanks for merging it. Good call on renaming it to Libraries.

**Pull request merged**
