### PR TITLE
86-113 of emberscreencasts.com added

### PR DESCRIPTION
**Pull request by jeffreybiles**
Does what it says in the title.  Updated up till next week.

### CODE REVIEW

**Comment by pootsbook** [comment]
:+1: That is some future cast love screen right there.

**Comment by jeffreybiles** [comment]
For a limited time they're EmberWatch.com exclusives! :)

**Comment by pootsbook** [comment]
:)

btw, if you could modify your script in future to include quotes around the titles that would be dandy. If a title has a colon in it, then YAML gets constipation.

**Comment by jeffreybiles** [comment]
Good catch, will do

**Pull request merged**
