### PR TITLE
refactor BOOM

### PR DESCRIPTION
**Pull request by nabilfreeman**
A couple more things need to be done to this before merging.

### CODE REVIEW

**Comment by nabilfreeman** [comment]
I totally rewrote `application.css`, and removed dependencies on foundation and foundicons as both are quite bloated. the new code is very lean.

still outstanding are a couple of random foundation references and i need to put an SVG file in for the Ember Watch logo (glasses icon)

**Comment by nabilfreeman** [comment]
I also changed the structure of a few things. The templates for rendering the lists needed a "metadata" div for easier styling.

I tidied up the "default" layout and added <div class="container"> everywhere to align things better.

We also use semantic html everywhere now apart from the tabs - I had weird problems with dl/dt/dd

**Comment by nabilfreeman** [comment]
Before:
screenshot 2015-06-25 22 00 39

After:
screenshot 2015-06-25 22 00 47

Design changes are pretty minor as this was more about getting the CSS back to a hackable state, but you can see I mainly just aligned some stuff up, tried to improve readability and bumped the spacing.

On mobile, the text used to go to the edges of the screen and now it looks a lot nicer too.

**Comment by nabilfreeman** [comment]
Mobile before:

screenshot 2015-06-25 22 05 43

Mobile after:

screenshot 2015-06-25 22 05 22

**Comment by pootsbook** [comment]
Love it. The mobile view is an improvement already :+1:

**Comment by nabilfreeman** [comment]
closes #28

**Pull request merged**
