### PR TITLE
Added video tutorial link

### PR DESCRIPTION
**Pull request by packtpartner**

### CODE REVIEW

**Comment by locks** [comment]
Appreciated!

**Comment by packtpartner** [comment]
Thanks for the merge. @locks can you tell me when will this reflect on http://emberwatch.com/tutorials.html

**Comment by locks** [comment]
@packtpartner hm it should be published right away, since we're using GitHub Pages. I'll try to debug it next week!

**Comment by packtpartner** [comment]
Thanks @locks I'll check in next week :)

**Comment by packtpartner** [comment]
Hi @locks , I'm sorry but I still don't see it. Could you look into it please?

**Comment by packtpartner** [comment]
@locks  unfortunately, I still don't see it on http://emberwatch.com/tutorials.html

**Comment by locks** [comment]
@packtpartner we seem to be having problems with the deploy, the commits after yours aren't in the deployed version yet. We've been focusing on porting the website to Ember, but we are now investigating the problem.

**Comment by locks** [comment]
@packtpartner seems fixed! http://emberwatch.com/tutorials

**Comment by packtpartner** [comment]
Thanks for looking into it @locks . Highly appreciated.

**Pull request merged**
